### PR TITLE
Replace icon images with Flaticon

### PR DESCRIPTION
**Pull request by j-tai**

### CODE REVIEW

**Review by AltheFlyer — COMMENTED** [review]
LGTM 👍

**Review by AltheFlyer — APPROVED** [review]

**Comment by AltheFlyer** [comment]
Tried to fix the merge conflict, lmk if I accidentally accepted the wrong thingy

**Comment by simcard0000** [comment]
@AltheFlyer You accepted the right thing but the merge conflict was going to take some wrangling (rn we don't need to see the collapse button on the left if the panel is alread docked) - I'll fix it :)

**Comment by j-tai** [comment]
> Tried to fix the merge conflict, lmk if I accidentally accepted the wrong thingy

Tysm for rebasing <333333333

**Review by AltheFlyer — APPROVED** [review]

**Pull request merged**
